#!/bin/sh

# Super+Shift+Return to start an instance of foot
riverctl map normal Super Return spawn foot

# Open the browser
riverctl map normal Super b spawn firefox

# Launcher
riverctl map normal Super Space spawn 'tofi-run | $SHELL'

# Screenshot (see XKB Keysym names for key symbol names)
riverctl map normal None 3270_PrintScreen spawn 'wayshot -s $(slurp) --stdout | wl-copy'

# Close the window
riverctl map normal Super+Shift Q close

# Switch focused window
riverctl map normal Super w focus-view next
riverctl map normal Super s focus-view previous

# Swap the focused view with the next/previous view in the layout stack
riverctl map normal Super+Shift w swap next
riverctl map normal Super+Shift s swap previous

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Shift H resize horizontal -100
riverctl map normal Super+Shift J resize vertical 100
riverctl map normal Super+Shift K resize vertical -100
riverctl map normal Super+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Tab toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'amixer set Master 5%+'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'amixer set Master 5%-'
    riverctl map $mode None XF86AudioMute         spawn 'amixer set Master toggle'

    # TODO: Brightness.
done

# Set background and border color
riverctl background-color 0xEBE5DF
riverctl border-color-focused 0x393263
riverctl border-color-unfocused 0xE5DBD1

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

# Touchpad configuration
riverctl input pointer-1739-52632-MSFT0004:00_06CB:CD98_Touchpad tap enabled
riverctl input pointer-1739-52632-MSFT0004:00_06CB:CD98_Touchpad natural-scroll enabled
riverctl input pointer-1739-52632-MSFT0004:00_06CB:CD98_Touchpad drag enabled

# Focus follows cursor
riverctl focus-follows-cursor normal

# Start notification daemon
riverctl spawn mako

# Start bar
riverctl spawn yambar

# Set up wallpaper
riverctl spawn "wbg ~/.wallpaper.png"

# Night light
riverctl spawn "wlsunset -l 43.65 -L 79.38 -t 5800 -T 6000"
