# Fonts we'll be re-using here and there
awesome: &awesome Font Awesome 6 Free:style=solid:pixelsize=14

# Default background for active river tags
bg_default: &bg_default {stack: [{background: {color: E5DBD1FF}}, {underline: {size: 4, color: 0C67A8FF}}]}

bar:
  height: 30
  location: top
  spacing: 7
  margin: 10

  # Default font
  font: Google Sans:pixelsize=15:weight=120

  foreground: 393263FF
  background: E5DBD1FF

  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 10
              right-margin: 13
              default: {string: {text: X, font: *awesome}}
              conditions:
                id == 1: {string: {text: 1}}
                id == 2: {string: {text: 2}}
                id == 3: {string: {text: 3}}
                id == 4: {string: {text: 4}}
                id == 5: {string: {text: 5}}
                id == 6: {string: {text: 6}}
                id == 7: {string: {text: 7}}
                id == 8: {string: {text: 8}}
                id == 9: {string: {text: 9}}
        content:
          map:
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: E9214FFF}}
              state == focused:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && occupied:
                map:
                  <<: *river_base
                  deco: {underline: {size: 4, color: BBAFB5FF}}
  center:
    - clock:
        time-format: "%H:%M %Z"
        content:
          - string: {text: "{time}"}
  right:
    - network:
        name: wlo1
        poll-interval: 1000
        content:
          map:
            default: {empty: {}}
            conditions:
              name == wlo1:
                map:
                  default: {string: {text: , font: *awesome}}
                  conditions:
                    state == down: {string: {text: , font: *awesome}}
                    state == up:
                      map:
                        default:
                          - string: {text: , font: *awesome}
                          - string: {text: " {ssid}"}

                        conditions:
                          ipv4 == "":
                            - string: {text: , font: *awesome}
                            - string: {text: " {ssid}"}
    - battery:
        name: BAT1
        poll-interval: 30000
        anchors:
          discharging: &discharging
            list:
              items:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                - string: {text: " {capacity}%"}
        content:
          map:
            conditions:
              state == unknown:
                <<: *discharging
              state == discharging:
                <<: *discharging
              state == charging:
                - string: {text: , foreground: 00ff00ff, font: *awesome}
                - string: {text: " {capacity}%"}
              state == full:
                - string: {text: , foreground: 00ff00ff, font: *awesome}
                - string: {text: " {capacity}%"}
              state == "not charging":
                - ramp:
                    tag: capacity
                    items:
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                      - string: {text:  , font: *awesome}
                - string: {text: " {capacity}%"}
    - label:
        content:
          string:
            on-click: systemctl poweroff
            text: 
            font: *awesome
